# fly.toml app configuration file generated for briefme on 2026-07-13T17:37:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'briefme'
primary_region = 'ams'

[build]
[env]
  PORT = '8080'

[[mounts]]
  source = 'briefme_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
